### PR TITLE
Fix 3d

### PR DESCRIPTION
**Pull request by ronwnor**
fixes 3d, and updates the css on the way.

### CODE REVIEW

**Comment by graphemecluster** [comment]
I actually planned to do this but finally decided to wait until 3D is supported in Desmos API 😅

**Comment by graphemecluster** [comment]
I actually planned to do this but eventually decided to wait until 3D is supported in Desmos API 😅

**Comment by ronwnor** [comment]
oh lol

**Comment by TETH-Main** [comment]
Do I have to update it every time when it is no longer supported?

**Comment by ronwnor** [comment]
I don't think so. the fix, weirdly enough, was to just add a "?" at the end of the url.
the updates are not related to the fix, but I thought it would be nice to include them.

Eli said that the API for 3d will release soon, so hopefully we can switch to that in the near future, from the current, somewhat-messy workaround.

**Pull request merged**
